CREATE TABLE `test`.`RULE` (
  `RULE_ID` INT NOT NULL AUTO_INCREMENT,
  `RULE_NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`RULE_ID`),
  UNIQUE INDEX `RULE_ID_UNIQUE` (`RULE_ID` ASC));

  
  ALTER TABLE `test`.`RULE` 
ADD COLUMN `STATUS` VARCHAR(45) NOT NULL DEFAULT 'ACTIVE' AFTER `LOCKED`;